# Generated by Django 3.0.4 on 2020-03-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Еmail'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя пользователя'),
        ),
    ]
