# Generated by Django 3.0.4 on 2020-03-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20200331_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
