# Generated by Django 3.0.4 on 2020-04-01 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PtoductInOrder',
            new_name='ProductInOrder',
        ),
    ]
