# Generated by Django 3.0.4 on 2020-04-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200401_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары задействованные в заказах (Admin)'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказа (Admin)'},
        ),
        migrations.AddField(
            model_name='productinorder',
            name='nmb',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='castomer_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='castomer_name',
            field=models.CharField(max_length=120, verbose_name='Имя заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='castomer_phone',
            field=models.CharField(blank=True, default=None, max_length=48, null=True, verbose_name='Телефон заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Комментарии к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=24, verbose_name='Статус заказа'),
        ),
    ]
